version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki-central
    ports:
      - "3100:3100"
    volumes:
      - ./config-centralizador/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-central
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

  promtail-local:
    image: grafana/promtail:latest
    container_name: promtail-central
    volumes:
      - /var/log:/var/log:ro
      - ./config-centralizador/promtail-local.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  grafana_data: